-- MySQL Script generated by MySQL Workbench
-- 04/03/15 20:47:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rbi_is
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rbi_is
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rbi_is` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `rbi_is` ;

-- -----------------------------------------------------
-- Table `rbi_is`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbi_is`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(225) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `contact_no` VARCHAR(45) NOT NULL,
  `house_no` VARCHAR(45) NOT NULL,
  `street` VARCHAR(225) NOT NULL,
  `city` VARCHAR(225) NOT NULL,
  `zip_code` INT NULL,
  `country` VARCHAR(225) NOT NULL,
  `email` VARCHAR(225) NOT NULL,
  `contact_person` VARCHAR(225) NULL,
  `create_date` TIMESTAMP NULL,
  `update_date` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbi_is`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbi_is`.`supplier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(225) NOT NULL,
  `contact_no` VARCHAR(45) NOT NULL,
  `contact_person` VARCHAR(225) NOT NULL,
  `house_no` VARCHAR(45) NOT NULL,
  `street` VARCHAR(225) NOT NULL,
  `city` VARCHAR(225) NOT NULL,
  `zip_code` INT NULL,
  `country` VARCHAR(225) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `create_date` TIMESTAMP NULL,
  `update_date` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbi_is`.`productinventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbi_is`.`productinventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(225) NOT NULL,
  `description` VARCHAR(225) NOT NULL,
  `qoh` INT NOT NULL,
  `items_sold` INT NOT NULL,
  `items_remaining` INT NULL,
  `price` DECIMAL NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `create_date` TIMESTAMP NULL,
  `update_date` TIMESTAMP NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`id`, `supplier_id`),
  INDEX `fk_productinventory_supplier1_idx` (`supplier_id` ASC),
  CONSTRAINT `fk_productinventory_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `rbi_is`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbi_is`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbi_is`.`purchase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NULL,
  `status` VARCHAR(45) NOT NULL,
  `num_items` INT NOT NULL,
  `total_amount` DECIMAL UNSIGNED NULL,
  `productinventory_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `productinventory_id`, `customer_id`),
  INDEX `fk_purchase_productinventory1_idx` (`productinventory_id` ASC),
  INDEX `fk_purchase_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_purchase_productinventory1`
    FOREIGN KEY (`productinventory_id`)
    REFERENCES `rbi_is`.`productinventory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `rbi_is`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbi_is`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbi_is`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NULL,
  `qty` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `productinventory_id` INT NOT NULL,
  PRIMARY KEY (`id`, `supplier_id`, `productinventory_id`),
  INDEX `fk_order_supplier_idx` (`supplier_id` ASC),
  INDEX `fk_order_productinventory1_idx` (`productinventory_id` ASC),
  CONSTRAINT `fk_order_supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `rbi_is`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_productinventory1`
    FOREIGN KEY (`productinventory_id`)
    REFERENCES `rbi_is`.`productinventory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
